baseurl = "https://stangirard.github.io/taskup"
title = "TaskUp"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "TaskUp"
  info = "Cooking 🥘"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/logo-taskup.png"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false